import Head from 'next/head'
import NavigationBar from '@/components/NavigationBar'
import NationalList from '@/components/NationalList'
import { useState } from 'react'

export default function Search() {
  const [show, setShow] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationBar />
        {!show && <span onClick={() => setShow(true)} className="fixed left-[20px] top-[150px] px-4 py-2 bg-[#363636] rounded-md text-white">Go</span>}
        {show && <span onClick={() => setShow(false)} className="fixed left-[20px] top-[150px] px-4 py-2 bg-[#363636] rounded-md text-white">Back</span>}
        {show ? <NationalList /> : null}
      </main>
    </>
  )
}
